spring.application.name=hello-springboot

#server.port=8081
spring.profiles.active=local

# H2 콘솔 활성화
spring.h2.console.enabled=true

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#H2 DB 설정
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JWT
jwt.secret="MySecretKeyForJwtToken1234567890!@#$"
jwt.expiration=3600000

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1000ms

# 이상한 swagger pet API목록을 안띄우도록..
springdoc.swagger-ui.disable-swagger-default-url=true


logging.level.org.hibernate.sql=off
logging.level.org.hibernate.type.descriptor.sql=off

