

spring.jpa.show-sql=true

logging.level.org.hibernate.sql=DEBUG

##MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=demo
spring.datasource.password=demo


spring.data.redis.host=localhost
spring.data.redis.port=6379

