spring.application.name=hello-springboot

server.port=8081

# H2 콘솔 활성화
spring.h2.console.enabled=true

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#H2 DB 설정
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


jwt.secret="MySecretKeyForJwtToken1234567890!@#$"
#1시간?
jwt.expiration=3600000

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=100ms

# 이상한 swagger pet API목록을 안띄우도록..
springdoc.swagger-ui.disable-swagger-default-url=true