

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.data.redis.host=redis
#spring.data.redis.port=6379
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=5000ms

spring.jpa.show-sql=false

logging.level.root=info
logging.level.org.hibernate.sql=off
logging.level.org.hibernate.type.descriptor.sql=off
logging.level.org.springframework.web=info
logging.level.org.springframework.security=info

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
